### ISSUE TITLE
关于官方指标测试工具

### ISSUE THREAD

**Issue by wsw321** [LiuShuaiyr/UAVMOT#12]
作者您好！请问您的官方MATLAB工具包的设置是怎样的呢？在evalMOT.m代码里设置了10个类别还是5个类别呢？谢谢。

**Comment by LiuShuaiyr** [comment]
5个类别。

**Comment by LiuShuaiyr** [comment]
> 作者您好！请问您的官方MATLAB工具包的设置是怎样的呢？在evalMOT.m代码里设置了10个类别还是5个类别呢？谢谢。

5个类别
