### ISSUE TITLE
数据文件形式

### ISSUE THREAD

**Issue by lebron-2016** [LiuShuaiyr/UAVMOT#13]
您好，请问源码当中您关于visdrone数据文件的形式是怎样处理的？官方数据集是一个视频对应一个标签文件，您这里好像是一个视频中的一帧对应一个标签文件。可以麻烦您分享一下数据集文件夹吗？万分感谢！！
![image](https://user-images.githubusercontent.com/80045218/211129530-5715a5f6-473b-4cda-9ab0-b6b19288efbc.png)

**Comment by lebron-2016** [comment]
还想向您请教一下，论文中MOTP的结果是根据py-motmetrics结果按如下方式换算的吗？
![image](https://user-images.githubusercontent.com/80045218/211235638-0ff10a80-b86e-4fc1-a6eb-847049ac8294.png)

**Comment by LiuShuaiyr** [comment]
> 您好，请问源码当中您关于visdrone数据文件的形式是怎样处理的？官方数据集是一个视频对应一个标签文件，您这里好像是一个视频中的一帧对应一个标签文件。可以麻烦您分享一下数据集文件夹吗？万分感谢！！ ![image](https://user-images.githubusercontent.com/80045218/211129530-5715a5f6-473b-4cda-9ab0-b6b19288efbc.png)
使用gen_dataset_visdrone.py 可生成对应的json文件，用于训练与测试。

**Comment by LiuShuaiyr** [comment]
> 还想向您请教一下，论文中MOTP的结果是根据py-motmetrics结果按如下方式换算的吗？ ![image](https://user-images.githubusercontent.com/80045218/211235638-0ff10a80-b86e-4fc1-a6eb-847049ac8294.png)



> 还想向您请教一下，论文中MOTP的结果是根据py-motmetrics结果按如下方式换算的吗？ ![image](https://user-images.githubusercontent.com/80045218/211235638-0ff10a80-b86e-4fc1-a6eb-847049ac8294.png)

使用的是官方测试代码，可参考https://github.com/VisDrone/VisDrone2018-MOT-toolkit

**Comment by xiaocc612** [comment]
> > 您好，请问源码当中您关于visdrone数据文件的形式是怎样处理的？官方数据集是一个视频对应一个标签文件，您这里好像是一个视频中的一帧对应一个标签文件。可以麻烦您分享一下数据集文件夹吗？万分感谢！！ ![image](https://user-images.githubusercontent.com/80045218/211129530-5715a5f6-473b-4cda-9ab0-b6b19288efbc.png)
> > 使用gen_dataset_visdrone.py 可生成对应的json文件，用于训练与测试。

你看看原repo: https://github.com/CaptainEven/MCMOT怎么生成的；评估是通过：https://github.com/VisDrone/VisDrone2018-MOT-toolkit官方工具。

**Comment by lebron-2016** [comment]
> > > 您好，请问源码当中您关于visdrone数据文件的形式是怎样处理的？官方数据集是一个视频对应一个标签文件，您这里好像是一个视频中的一帧对应一个标签文件。可以麻烦您分享一下数据集文件夹吗？万分感谢！！ ![image](https://user-images.githubusercontent.com/80045218/211129530-5715a5f6-473b-4cda-9ab0-b6b19288efbc.png)
> > > 使用gen_dataset_visdrone.py 可生成对应的json文件，用于训练与测试。
> 
> 你看看原repo: [https://github.com/CaptainEven/MCMOT怎么生成的；评估是通过：https://github.com/VisDrone/VisDrone2018-MOT-toolkit官方工具。](https://github.com/CaptainEven/MCMOT%E6%80%8E%E4%B9%88%E7%94%9F%E6%88%90%E7%9A%84%EF%BC%9B%E8%AF%84%E4%BC%B0%E6%98%AF%E9%80%9A%E8%BF%87%EF%BC%9Ahttps://github.com/VisDrone/VisDrone2018-MOT-toolkit%E5%AE%98%E6%96%B9%E5%B7%A5%E5%85%B7%E3%80%82)

好的，谢谢大佬！

**Comment by lebron-2016** [comment]
> > > 您好，请问源码当中您关于visdrone数据文件的形式是怎样处理的？官方数据集是一个视频对应一个标签文件，您这里好像是一个视频中的一帧对应一个标签文件。可以麻烦您分享一下数据集文件夹吗？万分感谢！！ ![image](https://user-images.githubusercontent.com/80045218/211129530-5715a5f6-473b-4cda-9ab0-b6b19288efbc.png)
> > > 使用gen_dataset_visdrone.py 可生成对应的json文件，用于训练与测试。
> 
> 你看看原repo: [https://github.com/CaptainEven/MCMOT怎么生成的；评估是通过：https://github.com/VisDrone/VisDrone2018-MOT-toolkit官方工具。](https://github.com/CaptainEven/MCMOT%E6%80%8E%E4%B9%88%E7%94%9F%E6%88%90%E7%9A%84%EF%BC%9B%E8%AF%84%E4%BC%B0%E6%98%AF%E9%80%9A%E8%BF%87%EF%BC%9Ahttps://github.com/VisDrone/VisDrone2018-MOT-toolkit%E5%AE%98%E6%96%B9%E5%B7%A5%E5%85%B7%E3%80%82)

好的，谢谢大佬！
还想问下您评估成功了吗？我使用https://github.com/VisDrone/VisDrone2018-MOT-toolkit 中的evalMOT.m文件评估自己生成的测试结果，指标显示都为0；我又评估作者在issue中提供的test_results.zip结果文件，指标依旧如下图所示。
![image](https://user-images.githubusercontent.com/80045218/211452916-3100cfb3-1895-411b-b1b4-6ceb56fa9e71.png)
可以再麻烦您提供一些帮助吗？万分感谢！！
