### ISSUE TITLE
关于官方测试

### ISSUE THREAD

**Issue by wsw321** [LiuShuaiyr/UAVMOT#15]
您好，感谢您的贡献。请问在测试test-dev数据集时，使用的是mask掉标签里无用区域的图片，还是没有做任何改变的原图呢？感谢答疑。

**Comment by LiuShuaiyr** [comment]
训练集使用的是mask掉标签里无用区域的图片，测试集使用的是原图。

**Comment by wsw321** [comment]
> 训练集使用的是mask掉标签里无用区域的图片，测试集使用的是原图。

好的，谢谢您的回答。
