### ISSUE TITLE
Hi, thank you very much for the code, I have a problem in the process of running

### ISSUE THREAD

**Issue by 972821054** [LiuShuaiyr/UAVMOT#3]
Hi, thank you very much for the code, I have a problem in the process of running。As shown below：
![image](https://user-images.githubusercontent.com/83146207/192753182-81eea5e1-ec47-4bac-9200-438a50f6c418.png)

Do you have any good comments? Thank you so much!

**Comment by HyeongChanHam** [comment]
solved using torch==1.4.0 and build correlation_package again
