### ISSUE TITLE
Hello, about the contrast test

### ISSUE THREAD

**Issue by 972821054** [LiuShuaiyr/UAVMOT#5]
Hello, thank you for your contribution to the MOT field!

I want to ask you about the comparative test. You tested the function of MOTR on the VisDrone dataset. I want to ask whether your training model is a multi category MOT or a single category (car) MOT?

If it is multi category, can you provide me with the modification location of relevant codes? I will be very grateful!

**Comment by LiuShuaiyr** [comment]
Our  training model is a multi category MOT, you can refer to the [gen_dataset_visdrone.py](https://github.com/LiuShuaiyr/UAVMOT/blob/master/src/gen_dataset_visdrone.py)
