### ISSUE TITLE
UAVDT和VisDrone实验中算法的结果文件

### ISSUE THREAD

**Issue by xyl-507** [LiuShuaiyr/UAVMOT#6]
作者您好
请问一下，能否提供UAVDT和VisDrone实验中所有算法的结果文件？
十分感谢！

**Comment by LiuShuaiyr** [comment]
目前提供了训练与测试代码。所有算法的结果文件涉及文件较多，待我们整理完成后一并上传至网盘，供大家参考。

**Comment by xiaocc612** [comment]
> 目前提供了训练与测试代码。所有算法的结果文件涉及文件较多，待我们整理完成后一并上传至网盘，供大家参考。

作者您好。
    请问paper中的测试结果文件处理好了吗？你们训练好的模型可否分享下？另外，目前realse的代码中，分类分支包含triplet loss时，训练报错，而paper中明确说明使用triplet loss了。另外，请问若不是使用triplet loss, performance会差多少呢？
