### ISSUE TITLE
Multi classification or single classification？

### ISSUE THREAD

**Issue by 972821054** [LiuShuaiyr/UAVMOT#7]
Hello, thank you for your contribution to the MOT field!

I want to ask you about the results of single category multi-target tracking or multi category multi-target tracking on the VisDrone test set?

I would appreciate your reply!

**Comment by LiuShuaiyr** [comment]
Hi, @972821054 , the VisDrone test set is divided into test-dev set and test-challenge set, we do experiments on VisDrone test-dev set with multi category multi-target tracking, and we get the 36.1% MOTA, please refer to the paper "Multi-Object Tracking Meets Moving UAV."

**Comment by 972821054** [comment]
@LiuShuaiyr Thank you for your reply!

I want to ask you about the MOTR code. Did you change the MOTR code to multi category and multi target tracking? I think its code only supports single category multi-target tracking
