### ISSUE TITLE
about LOSS

### ISSUE THREAD

**Issue by 972821054** [LiuShuaiyr/UAVMOT#9]
![image](https://user-images.githubusercontent.com/83146207/198828376-1b754f6b-9951-48b1-b66e-063f10238ded.png)
Hello, I run your code, and the loss in training is shown in the figure above

and The changes I made are shown in the figure below. If I don't make changes, this error will occur. How do you avoid this error?
![image](https://user-images.githubusercontent.com/83146207/198828525-638d4dc3-729e-4730-b26d-aeb14edc1c36.png)

![image](https://user-images.githubusercontent.com/83146207/198828476-3821ac98-52ba-4a8e-b3e6-e96e9dc808b2.png)

**Comment by Shengjia-C** [comment]
I have same problem. Have you solved the problem? @972821054

**Comment by 972821054** [comment]
@Shengjia-C Hello, I haven't solved this problem. After I changed the reid loss to something else, it still appears. Compared with the mcmot algorithm, I feel that an error occurred when taking the pre. But I didn't look down.

**Comment by xiaocc612** [comment]
@LiuShuaiyr Does the author have time to deal with this bug? We all encountered the same problem when training the network.

**Comment by LiuShuaiyr** [comment]
> @LiuShuaiyr Does the author have time to deal with this bug? We all encountered the same problem when training the network.

I have re trained and the normal training is shown as follows：

!
<img width="931" alt="1671946485267" src="https://user-images.githubusercontent.com/33255300/209458578-6b33c95d-55a4-4fd6-902e-95e14b72e35d.png">

**Comment by xiaocc612** [comment]
> > @LiuShuaiyr Does the author have time to deal with this bug? We all encountered the same problem when training the network.
> 
> I have re trained and the normal training is shown as follows：
> 
> ! <img alt="1671946485267" width="931" src="https://user-images.githubusercontent.com/33255300/209458578-6b33c95d-55a4-4fd6-902e-95e14b72e35d.png">

The problem should be here https://github.com/LiuShuaiyr/UAVMOT/blob/9b222ac15f967b89ae5c3de039b1c37e28af6fe3/src/lib/datasets/dataset/jde.py#L710 , the pre-image path is not configured correctly, after modifying，the loss becomes normal. It is worth noting that if triplet loss is used, an error will still be reported.

**Comment by Jyerim** [comment]
we need to change models/losses.py in line 726 with
'#dist_an.append(dist[i][mask[i] == 0].min().unsqueeze(0))
dist_an.append(dist[i][1 + (-1)*mask[i]].min().unsqueeze(0))`
